### ISSUE TITLE
Create Flowchart

### ISSUE THREAD

**Issue by shassen** [shassen/news-crews#13]
- [x] Finalize

**Comment by shassen** [comment]
@jasonseminara Please review this flowchart:

![screen shot 2018-08-03 at 9 57 04 am](https://user-images.githubusercontent.com/34017019/43646710-a266a806-9703-11e8-8f31-35e723162023.png)

**Comment by jasonseminara** [comment]
This is comprehensible, but some of the symbols are wrong. Please use
diamonds to ask questions. It looks like the only thing I can do after the
landing page is log in. Is that true?



Sent from Astro <https://www.helloastro.com> for Mac

On Aug 3, 2018 at 10:13 AM, Shawn <notifications@github.com> wrote:


@jasonseminara <https://github.com/jasonseminara> Please review this
flowchart:

[image: screen shot 2018-08-03 at 9 57 04 am]
<https://user-images.githubusercontent.com/34017019/43646710-a266a806-9703-11e8-8f31-35e723162023.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/shassen/news-crews/issues/13#issuecomment-410262439>,
or mute the thread
